#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
GIT=(git -c "safe.directory=$ROOT")

fail() {
    echo "source-audit: $*" >&2
    exit 1
}

require_file() {
    [[ -f "$1" ]] || fail "missing required source file: $1"
}

# These files are part of the distributable source tree: the app license,
# dependency notice, generated-project specification, and compatibility gate.
require_file LICENSE
require_file LICENSES/SwiftProtobuf-Apache-2.0.txt
require_file PrivacyInfo.xcprivacy
require_file project.yml
require_file scripts/ios14-audit.sh
require_file TieBaX/Resources/Info.plist
require_file TieBaX/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
require_file TieBaX/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png

grep -Fq "GNU GENERAL PUBLIC LICENSE" LICENSE \
    || fail "LICENSE is not the expected GPL notice"
grep -Fq "Apache License" LICENSES/SwiftProtobuf-Apache-2.0.txt \
    || fail "SwiftProtobuf license notice is missing"
grep -Fq "exactVersion: 1.38.1" project.yml \
    || fail "SwiftProtobuf must remain pinned to the reviewed version"
grep -Fq "<key>CFBundleIconName</key>" TieBaX/Resources/Info.plist \
    || fail "Info.plist must declare the AppIcon asset name"
grep -Fq "<string>AppIcon</string>" TieBaX/Resources/Info.plist \
    || fail "Info.plist must point to the AppIcon asset"
grep -Fq "ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon" project.yml \
    || fail "project.yml must compile the AppIcon asset catalog"
if ! grep -A2 -F "path: TieBaX/Resources/Assets.xcassets" project.yml \
    | grep -Fq "buildPhase: resources"; then
    fail "project.yml must place Assets.xcassets in the resources phase"
fi

# The project identity must not regress to a legacy reference-app name.
legacy_prefix="$(printf 'Tieba%s' 'Pure')"
legacy_paths="(^|/)("
for suffix in "" "OpenIn" "Tests" "UITests" "Profile"; do
    legacy_paths="$legacy_paths$legacy_prefix$suffix|"
done
legacy_paths="${legacy_paths%|})(/|$)"
if "${GIT[@]}" ls-files | grep -E "$legacy_paths" >/dev/null; then
    fail "a legacy reference-app directory remains in the project tree"
fi
if grep -E "$legacy_prefix(/|OpenIn|Tests|UITests|Profile)" project.yml >/dev/null; then
    fail "project.yml still references a legacy reference-app path"
fi

# Only reviewed, declared dependencies may be shipped. A checkout containing
# vendored frameworks or package managers outside project.yml is a release
# blocker because their source and license notices would be unknown.
if "${GIT[@]}" ls-files | grep -E '(^|/)(Pods|Carthage|Vendor|Frameworks)/|\.(framework|xcframework)$' >/dev/null; then
    fail "unreviewed vendored framework or dependency directory is tracked"
fi

# Credentials and signing material must never enter the source release.
if "${GIT[@]}" ls-files | grep -E '(^|/)(account\.json|\.env($|\.)|.*\.(p12|p8|pem|key|mobileprovision))$' >/dev/null; then
    fail "credential or signing material is tracked"
fi

# The generated Xcode project is intentionally not a source artifact. CI must
# create it from project.yml when it needs to compile the source tree.
if "${GIT[@]}" ls-files | grep -E '(^|/)TieBaX\.xcodeproj/' >/dev/null; then
    fail "generated Xcode project is tracked; use project.yml instead"
fi

proto_files="$("${GIT[@]}" ls-files 'TieBaX/Core/Protobuf/Generated/*.pb.swift')"
[[ -n "$proto_files" ]] || fail "no generated protobuf sources are tracked"
while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    grep -Fq "Generated by the Swift generator plugin" "$path" \
        || fail "protobuf source lacks generated-code provenance: $path"
done <<< "$proto_files"

echo "source-audit: source tree, license notices, pinned dependency,"
echo "project identity, generated protobuf provenance, and secret exclusions OK"
