#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
GIT=(git -c "safe.directory=$ROOT")

fail() {
    echo "source-audit: $*" >&2
    exit 1
}

require_file() {
    [[ -f "$1" ]] || fail "missing required file: $1"
}

require_file LICENSE
require_file LICENSES/SwiftProtobuf-Apache-2.0.txt
require_file docs/reference-baseline.md
require_file docs/real-interface-validation.md
require_file project.yml
require_file scripts/ios14-audit.sh

grep -Fq "GNU GENERAL PUBLIC LICENSE" LICENSE \
    || fail "LICENSE is not the expected GPL notice"
grep -Fq "Apache License" LICENSES/SwiftProtobuf-Apache-2.0.txt \
    || fail "SwiftProtobuf license notice is missing"
grep -Fq "exactVersion: 1.38.1" project.yml \
    || fail "SwiftProtobuf must remain pinned to the reviewed version"

for reference in TiebaLite TiebaPure-iOS aiotieba tbclient.protobuf; do
    grep -Fq "$reference" docs/reference-baseline.md \
        || fail "reference boundary is missing: $reference"
done

if "${GIT[@]}" ls-files | grep -E '(^|/)(TiebaPure|TiebaPureOpenIn|TiebaPureTests|TiebaPureUITests|TiebaPureProfile)(/|$)' >/dev/null; then
    fail "legacy TiebaPure directory remains in the project tree"
fi
if grep -E 'TiebaPure(/|OpenIn|Tests|UITests|Profile)' project.yml >/dev/null; then
    fail "project.yml still references a legacy TiebaPure path"
fi

# Only reviewed, declared dependencies may be shipped. A checkout containing
# vendored frameworks or package managers outside project.yml is a release
# blocker because their source and license notices would be unknown.
if "${GIT[@]}" ls-files | grep -E '(^|/)(Pods|Carthage|Vendor|Frameworks)/|\.(framework|xcframework)$' >/dev/null; then
    fail "unreviewed vendored framework or dependency directory is tracked"
fi

# Credentials and signing material must never enter the source release.
if "${GIT[@]}" ls-files | grep -E '(^|/)(account\.json|\.env($|\.)|.*\.(p12|p8|pem|key|mobileprovision))$' >/dev/null; then
    fail "credential or signing material is tracked"
fi

# The generated Xcode project is intentionally not a source artifact. CI must
# create it from project.yml after this audit.
if "${GIT[@]}" ls-files | grep -E '(^|/)TieBaX\.xcodeproj/' >/dev/null; then
    fail "generated Xcode project is tracked; use project.yml instead"
fi

proto_files="$("${GIT[@]}" ls-files 'TieBaX/Core/Protobuf/Generated/*.pb.swift')"
[[ -n "$proto_files" ]] || fail "no generated protobuf sources are tracked"
while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    grep -Fq "Generated by the Swift generator plugin" "$path" \
        || fail "protobuf source lacks generated-code provenance: $path"
done <<< "$proto_files"

echo "source-audit: GPL notice, SwiftProtobuf Apache notice, pinned dependency,"
echo "source boundaries, generated protobuf provenance, and secret exclusions OK"
